ferry/accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "oidc/redirect/",
        views.SSOOIDCRedirectView.as_view(),
        name="sso_oidc_redirect",
    ),
    path("unlinked/", views.UnlinkedAccountView.as_view(), name="unlinked_account"),
    path("people/", views.PersonListView.as_view(), name="person-list"),
    path("people/<uuid:pk>/", views.PersonDetailView.as_view(), name="person-detail"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/api-tokens/", views.ProfileAPITokenView.as_view(), name="api-tokens"),
    path("profile/api-tokens/new/", views.CreateAPITokenView.as_view(), name="api-token-create"),
    path("profile/api-tokens/<uuid:pk>/activate/", views.ReactivateAPITokenView.as_view(), name="api-tokens-activate"),
    path(
        "profile/api-tokens/<uuid:pk>/deactivate/", views.DeactivateAPITokenView.as_view(), name="api-tokens-deactivate"
    ),
]

ferry/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from ferry.core.api.router import urls as api_urls

urlpatterns = []

urlpatterns = [
    path("", include("ferry.dashboard.urls", namespace="dashboard")),
    path("accounts/", include("ferry.accounts.urls")),
    path("ferries/", include("ferry.court.urls", namespace="court")),
    path("pub/", include("ferry.pub.urls", namespace="pub")),
    path("admin/", admin.site.urls),
    path("api/", TemplateView.as_view(template_name="api_index.html")),
    # API v2
    path("api/v2/schema/", SpectacularAPIView.as_view(), name="api-v2-schema"),
    path("api/v2/docs/", SpectacularSwaggerView.as_view(url_name="api-v2-schema"), name="api-v2-docs"),
    path("api/v2/", include((api_urls, "api-2.0.0"), namespace="api")),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

ferry/court/urls.py
from django.urls import path

from . import views

app_name = "court"

urlpatterns = [
    path("consequences/", views.ConsequenceListView.as_view(), name="consequence-list"),
    path(
        "consequences/<uuid:pk>/deactivate/", views.DeactivateConsequenceView.as_view(), name="consequence-deactivate"
    ),
    path("consequences/new/", views.ConsequenceCreateView.as_view(), name="consequence-create"),
]

ferry/pub/urls.py
from django.urls import path

from . import views

app_name = "pub"

urlpatterns = [
    path("events", views.PubEventListView.as_view(), name="events-list"),
    path("events/<uuid:pk>/", views.PubEventDetailView.as_view(), name="events-detail"),
    path("events/<uuid:pk>/rsvp/", views.PubEventManualRSVPView.as_view(), name="events-manual-rsvp"),
    path("event/<uuid:pk>/booking/add/", views.AddPubEventBookingView.as_view(), name="events-add-booking"),
    path("event/<uuid:pk>/update-response/", views.UpdatePubEventResponseView.as_view(), name="events-update-response"),
]

ferry/court/forms.py
from typing import Any

from crispy_forms.bootstrap import (
    PrependedText,
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django import forms

from ferry.accounts.models import Person
from ferry.court.models import Consequence


class ConsequenceCreateForm(forms.ModelForm):
    content = forms.CharField(label="Sentence", max_length=150)

    class Meta:
        model = Consequence
        fields = ("content",)

    def __init__(self, *args: Any, person: Person, **kwargs: Any) -> None:
        self.person = person
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            PrependedText("content", "$player has been sentenced to"),
        )
        self.helper.add_input(Submit("submit", "Create Consequence"))

    def save(self, commit: bool = True) -> Any:  # noqa: FBT001, FBT002
        self.instance.created_by = self.person
        return super().save(commit)

ferry/accounts/api/views.py
import base64
from typing import Any

from django.core.signing import TimestampSigner
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import exceptions, filters, permissions, serializers, viewsets
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response

from ferry.accounts.models import Person, PersonQuerySet, User

from .serializers import (
    DiscordLinkTokenSerializer,
    PersonSerializer,
    UserSerializer,
)


class UserViewset(viewsets.GenericViewSet):
    serializer_class = UserSerializer

    @extend_schema(tags=["Users"], description="Get the current user")
    @action(detail=False)
    def me(self, request: Request) -> Response:
        serializer = self.get_serializer(request.user)
        return Response(serializer.data)


class PeopleObjectPermission(permissions.BasePermission):
    def has_permission(self, request: Request, view: Any) -> bool:
        if request.method in permissions.SAFE_METHODS:
            return True

        if request.method in ["PUT", "PATCH", "DELETE"]:
            return True

        if request.method == "POST":
            return request.user.has_perm("court.create_person")

        return False

    def has_object_permission(self, request: Request, view: Any, obj: Any) -> bool:
        if request.method in permissions.SAFE_METHODS:
            return True

        if request.method in ["PUT", "PATCH"]:
            return request.user.has_perm("court.edit_person", obj)

        if request.method == "DELETE":
            return request.user.has_perm("court.delete_person", obj)

        return False


@extend_schema_view(
    list=extend_schema(tags=["People"]),
    retrieve=extend_schema(tags=["People"]),
    update=extend_schema(tags=["People"]),
    partial_update=extend_schema(tags=["People"]),
    create=extend_schema(tags=["People"]),
    destroy=extend_schema(tags=["People"]),
)
class PersonViewset(viewsets.ModelViewSet):
    serializer_class = PersonSerializer
    filter_backends = [filters.OrderingFilter, DjangoFilterBackend]
    permission_classes = [permissions.IsAuthenticated, PeopleObjectPermission]
    ordering_fields = ("display_name", "current_score", "created_at", "updated_at")
    filterset_fields = ("discord_id", "autopub")

    def get_queryset(self) -> PersonQuerySet:
        assert self.request.user.is_authenticated
        return Person.objects.for_user(self.request.user).with_current_score()

    def perform_update(self, serializer: serializers.BaseSerializer) -> None:
        assert serializer.instance
        if all(
            [
                serializer.instance.discord_id != serializer.validated_data.get("discord_id"),
                not serializer.context["request"].user.has_perm("court.assign_discord_id_to_person"),
            ]
        ):
            raise exceptions.PermissionDenied("You don't have permission to update a Discord ID directly.")
        return super().perform_update(serializer)

    @extend_schema(
        tags=["People"],
        responses={200: DiscordLinkTokenSerializer},
        description="This is used by the Discord bot only.",
    )
    @action(detail=True, methods=["GET"], permission_classes=[permissions.IsAuthenticated])
    def fact(self, request: Request, pk: None = None) -> Response:
        person = self.get_object()
        if not request.user.has_perm("court.act_for_person", person):
            raise exceptions.PermissionDenied("You don't have permission to get a FACT for that person.")

        try:
            _ = person.user
            link_token = None
        except User.DoesNotExist:
            signer = TimestampSigner()
            link_token = base64.b64encode(signer.sign(str(person.id)).encode()).decode()

        serializer = DiscordLinkTokenSerializer({"link_token": link_token, "fact": "bees"})
        return Response(serializer.data)

ferry/accounts/views.py
from __future__ import annotations

from typing import Any, cast
from uuid import UUID

from django import http
from django.contrib import messages
from django.contrib.auth import login, mixins
from django.contrib.auth import views as auth_views
from django.core.exceptions import SuspiciousOperation
from django.db import models
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, FormView, ListView, UpdateView, View

from ferry.accounts.forms import CreateAPITokenForm, PersonProfileForm, UserPersonLinkForm
from ferry.accounts.models import Person
from ferry.core.http import HttpRequest
from ferry.core.mixins import BreadcrumbsMixin
from ferry.court.models import Accusation

from .models import APIToken, PersonQuerySet, User
from .oauth import oauth_config


class LoginView(auth_views.LoginView):
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponse:  # type: ignore[override]
        # Redirect a user that is already logged in.
        # Borrowed from django.contrib.auth.views.LoginView.dispatch
        if self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return http.HttpResponseRedirect(redirect_to)

        # Redirect to SSO immediately.
        request.session["sso_next"] = self.get_redirect_url()

        redirect_uri = request.build_absolute_uri(reverse("accounts:sso_oidc_redirect"))
        return oauth_config.sown.authorize_redirect(request, redirect_uri)


class SSOOIDCRedirectView(View):
    def get(self, request: HttpRequest) -> http.HttpResponseRedirect | http.HttpResponseServerError:
        token = oauth_config.sown.authorize_access_token(request)
        userinfo = token.get("userinfo", {})

        try:
            username = userinfo["sub"]
        except KeyError:
            return http.HttpResponseServerError("Invalid response from SSO.")

        user, _ = User.objects.get_or_create(username=username)

        self.update_user(user, userinfo)

        login(request, user, backend="django.contrib.auth.backends.ModelBackend")

        from_session = request.session.pop("sso_next", None)

        redirect_to = from_session or "/"
        messages.info(request, f"Signed in via SOWN SSO. Welcome {user.get_short_name()}")
        return redirect(redirect_to)

    def update_user(self, user: User, claims: dict[str, bool | str | list[str]]) -> User:
        full_name = str(claims.get("given_name", ""))

        name_parts = full_name.split(" ")

        if len(name_parts) == 0:
            return user
        elif len(name_parts) == 1:
            user.first_name = name_parts[0]
            user.last_name = ""
        else:
            user.first_name = name_parts.pop(0)
            user.last_name = " ".join(name_parts)

        if email := claims.get("email"):
            user.email = str(email)

        user.save()

        return user


class UnlinkedAccountView(mixins.LoginRequiredMixin, FormView):
    template_name = "accounts/unlinked.html"
    form_class = UserPersonLinkForm
    success_url = reverse_lazy("dashboard:scoreboard")

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> http.HttpResponseBase:  # type: ignore[override]
        assert request.user.is_authenticated

        if request.user.person is not None:
            return redirect("dashboard:scoreboard")

        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form: UserPersonLinkForm) -> http.HttpResponse:
        form.save()
        messages.info(self.request, "Your Discord account has been successfully linked.")
        return super().form_valid(form)


class PersonListView(mixins.LoginRequiredMixin, BreadcrumbsMixin, ListView):
    template_name = "accounts/person_list.html"
    breadcrumbs = [(None, "People")]

    def get_queryset(self) -> PersonQuerySet:
        assert self.request.user.is_authenticated
        qs = Person.objects.for_user(self.request.user)
        qs = qs.order_by(models.functions.Lower("display_name"))
        return qs


class PersonDetailView(mixins.LoginRequiredMixin, BreadcrumbsMixin, DetailView):
    model = Person
    template_name = "accounts/person_detail.html"

    def get_breadcrumbs(self) -> list[tuple[str | None, str]]:
        return super().get_breadcrumbs() + [
            (reverse_lazy("accounts:person-list"), "People"),
            (None, self.object.display_name),
        ]

    def get_queryset(self) -> PersonQuerySet:
        qs = cast(PersonQuerySet, super().get_queryset())
        qs = qs.with_current_score()
        qs = qs.with_num_ratified_accusations()
        return qs

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        assert self.request.user.is_authenticated
        qs = Accusation.objects.for_user(self.request.user)
        qs = qs.filter(models.Q(suspect=self.object) | models.Q(created_by=self.object))
        qs = qs.order_by("-created_at")

        return super().get_context_data(accusations=qs, **kwargs)


class ProfileView(mixins.LoginRequiredMixin, BreadcrumbsMixin, UpdateView):
    form_class = PersonProfileForm
    template_name = "accounts/profile.html"
    success_url = reverse_lazy("accounts:profile")
    breadcrumbs = [(None, "My Profile")]

    def get_object(self, queryset: QuerySet[Any] | None = None) -> Person:
        assert self.request.user.is_authenticated
        assert self.request.user.person
        return self.request.user.person

    def form_valid(self, form: BaseModelForm) -> http.HttpResponse:
        messages.info(self.request, "Updated profile.")
        return super().form_valid(form)


class CreateAPITokenView(mixins.LoginRequiredMixin, BreadcrumbsMixin, CreateView):
    model = APIToken
    form_class = CreateAPITokenForm
    template_name = "accounts/api_token_create.html"
    success_url = reverse_lazy("accounts:api-tokens")
    breadcrumbs = [(reverse_lazy("accounts:profile"), "My Profile"), (None, "Create API Token")]

    def form_valid(self, form: BaseModelForm) -> http.HttpResponse:
        form.instance.user = self.request.user
        resp = super().form_valid(form)

        assert self.object
        messages.info(self.request, f'Your new token is: "{self.object.token}"')
        return resp


class ProfileAPITokenView(mixins.LoginRequiredMixin, BreadcrumbsMixin, ListView):
    template_name = "accounts/api_tokens.html"
    success_url = reverse_lazy("accounts:api-tokens")
    breadcrumbs = [(None, "My Profile")]

    def get_queryset(self) -> QuerySet[APIToken]:
        assert self.request.user.is_authenticated
        return self.request.user.api_tokens.all()


class DeactivateAPITokenView(mixins.LoginRequiredMixin, View):
    new_state = False

    def post(self, request: HttpRequest, pk: UUID) -> http.HttpResponse:
        assert request.user.is_authenticated

        if not request.htmx:
            raise SuspiciousOperation("That request is not valid.")

        api_token = get_object_or_404(request.user.api_tokens, id=pk)
        api_token.is_active = self.new_state
        api_token.save()

        return render(request, "accounts/api_tokens__table_row.html", {"api_token": api_token})


class ReactivateAPITokenView(DeactivateAPITokenView):
    new_state = True

ferry/dashboard/views.py
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.db.models.functions import DenseRank
from django.views.generic import ListView

from ferry.accounts.models import Person, PersonQuerySet
from ferry.core.mixins import BreadcrumbsMixin
from ferry.court.models import Accusation


class ScoreboardView(LoginRequiredMixin, BreadcrumbsMixin, ListView):
    template_name = "dashboard/scoreboard.html"

    def get_queryset(self) -> PersonQuerySet:
        assert self.request.user.is_authenticated
        qs = Person.objects.for_user(self.request.user)
        qs = qs.with_current_score()
        qs = qs.with_num_ratified_accusations()
        qs = qs.annotate(rank=models.Window(expression=DenseRank(), order_by=models.F("current_score").desc()))
        qs = qs.filter(models.Q(current_score__gt=0) | models.Q(num_ratified_accusations__gt=0))

        qs = qs.order_by("rank", "-current_score", "-num_ratified_accusations")
        return qs


class RecentAccusationsView(LoginRequiredMixin, BreadcrumbsMixin, ListView):
    template_name = "dashboard/recent-accusations.html"

    def get_queryset(self) -> models.QuerySet[Any]:
        assert self.request.user.is_authenticated
        qs = Accusation.objects.for_user(self.request.user)
        qs = qs.order_by("-created_at")
        return qs

ferry/templates/pub/inc/booking_details.html
{% load crispy_forms_tags %}
<div class="card mt-2">
  <div class="card-body">
    <h5 class="card-title">Booking</h5>
    {% if booking %}
      <p>A table has been booked by {{ booking.created_by }} booked for <strong>{{ booking.table_size }}</strong> people.</p>
      <p>However, there is likely to be more space if needed, so please do not be put off coming if you are late responding to the event.</p>
    {% else %}
      {% if event.is_past %}
        <p>No booking information available for this event.</p>
      {% else %}
        <p>This event has not been booked with the venue yet.</p>
        {% crispy form %}
      {% endif %}
    {% endif %}
  </div>
</div>

ferry/templates/pub/inc/event_details.html
{% load rules %}
<div class="container event-details">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Information</h5>
          <dl class="row">
            <dt class="col-sm-3">Date</dt>
            <dd class="col-sm-9">{{ event.timestamp }}</dd>

            <dt class="col-sm-3">Location</dt>
            <dd class="col-sm-9">
              {% if event.table %}{{ event.table }}{% else %}{{ event.pub }}{% endif %}<br/>
              <a href="{{ event.pub.map_url }}">Map</a>
            </dd>

            {% if event.pub.menu_url %}
              <dt class="col-sm-3">Menu</dt>
              <dd class="col-sm-9"><a href="{{ event.pub.menu_url }}">View Menu</a></dd>
            {% endif %}
          </dl>
        </div>
      </div>
      <div class="card mt-2">
        <div class="card-body">
          <h5 class="card-title">Attendance</h5>
          {% if rsvp %}
            {% if rsvp.method == "A" %}
              <p>You have automatically said yes using AutoPub.</p>
              {% if not event.is_past %}
                <button class="btn btn-sm btn-danger"
                        hx-post="{% url 'pub:events-update-response' event.id %}"
                        hx-target="closest .event-details"
                        hx-swap='outerHTML'
                >
                  I won't be coming
                </button>
              {% endif %}
            {% elif rsvp.method == "D" %}
              <p>You marked interest in this pub on Discord.</p>
              <p>If you are no longer going to come, please remove your interest on the Discord event.</p>
            {% elif rsvp.method == "W" %}
              {% if rsvp.is_attending %}
                <p>You said yes to this pub via this web interface.</p>
                {% if not event.is_past %}
                  <button class="btn btn-sm btn-danger"
                          hx-post="{% url 'pub:events-update-response' event.id %}"
                          hx-target="closest .event-details"
                          hx-swap='outerHTML'
                  >
                    I'm not coming anymore!
                  </button>
                {% endif %}
              {% else %}
                <p>You said no to this pub via this web interface. </p>
                <p>That usually means you opted-out of AutoPub.</p>
                {% if not event.is_past %}
                  <button class="btn btn-sm btn-success"
                          hx-post="{% url 'pub:events-update-response' event.id %}"
                          hx-target="closest .event-details"
                          hx-swap='outerHTML'
                  >
                    I'm actually coming
                  </button>
                {% endif %}
              {% endif %}
            {% endif %}
          {% else %}
            {% if event.is_past %}
              <p>You did not respond to this pub.</p>
            {% else %}
              <p>You have not responded to this pub yet.</p>
              <button class="btn btn-sm btn-success"
                      hx-post="{% url 'pub:events-update-response' event.id %}"
                      hx-target="closest .event-details"
                      hx-swap='outerHTML'
              >
                I'm coming!
              </button>
            {% endif %}
          {% endif %}
        </div>
      </div>
      {% include "pub/inc/booking_details.html" with booking=booking form=booking_form %}
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Attendees ({{ attendees|length }})</h5>
          <ul class="list-group list-group-flush">
            {% for attendee in attendees %}
              <a class="list-group-item list-group-item-action" href="{% url 'accounts:person-detail' attendee.id %}">{{ attendee }}</a>
            {% empty %}
              <p>There are no attendees.</p>
            {% endfor %}
          </ul>
          {% has_perm 'pub.record_attendance' request.user as can_record_attendance %}
          {% if can_record_attendance %}
            <a class="btn btn-danger mt-3" href="{% url 'pub:events-manual-rsvp' event.id %}">Add manual RSVP</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>